
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND OR NOT LPAREN RPAREN ASSIGN IDrule : ID ASSIGN expressionexpression : expression AND termexpression : expression OR termexpression : termterm : NOT termterm : IDterm : LPAREN expression RPAREN'
    
_lr_action_items = {'AND':([4,5,8,9,10,13,14,15,],[-4,-6,11,11,-5,-7,-2,-3,]),'OR':([4,5,8,9,10,13,14,15,],[-4,-6,12,12,-5,-7,-2,-3,]),'RPAREN':([4,5,9,10,13,14,15,],[-4,-6,13,-5,-7,-2,-3,]),'ASSIGN':([1,],[3,]),'LPAREN':([3,6,7,11,12,],[6,6,6,6,6,]),'NOT':([3,6,7,11,12,],[7,7,7,7,7,]),'ID':([0,3,6,7,11,12,],[1,5,5,5,5,5,]),'$end':([2,4,5,8,10,13,14,15,],[0,-4,-6,-1,-5,-7,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([3,6,7,11,12,],[4,4,10,14,15,]),'expression':([3,6,],[8,9,]),'rule':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> rule","S'",1,None,None,None),
  ('rule -> ID ASSIGN expression','rule',3,'p_rule','boolparser.py',52),
  ('expression -> expression AND term','expression',3,'p_expression_and','boolparser.py',64),
  ('expression -> expression OR term','expression',3,'p_expression_or','boolparser.py',80),
  ('expression -> term','expression',1,'p_expression_term','boolparser.py',96),
  ('term -> NOT term','term',2,'p_term_not','boolparser.py',101),
  ('term -> ID','term',1,'p_term','boolparser.py',108),
  ('term -> LPAREN expression RPAREN','term',3,'p_term_expr','boolparser.py',114),
]
